languages = [
    ('aa', 'Afar'),
    ('ab', 'Abkhazian'),
    ('af', 'Afrikaans'),
    ('ak', 'Akan'),
    ('sq', 'Albanian'),
    ('am', 'Amharic'),
    ('ar', 'Arabic'),
    ('an', 'Aragonese'),
    ('hy', 'Armenian'),
    ('as', 'Assamese'),
    ('av', 'Avaric'),
    ('ae', 'Avestan'),
    ('ay', 'Aymara'),
    ('az', 'Azerbaijani'),
    ('ba', 'Bashkir'),
    ('bm', 'Bambara'),
    ('eu', 'Basque'),
    ('be', 'Belarusian'),
    ('bn', 'Bengali'),
    ('bh', 'Bihari languages'),
    ('bi', 'Bislama'),
    ('bo', 'Tibetan'),
    ('bs', 'Bosnian'),
    ('br', 'Breton'),
    ('bg', 'Bulgarian'),
    ('my', 'Burmese'),
    ('ca', 'Catalan; Valencian'),
    ('cs', 'Czech'),
    ('ch', 'Chamorro'),
    ('ce', 'Chechen'),
    ('zh', 'Chinese'),
    ('cu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
    ('cv', 'Chuvash'),
    ('kw', 'Cornish'),
    ('co', 'Corsican'),
    ('cr', 'Cree'),
    ('cy', 'Welsh'),
    ('cs', 'Czech'),
    ('da', 'Danish'),
    ('de', 'German'),
    ('dv', 'Divehi; Dhivehi; Maldivian'),
    ('nl', 'Dutch; Flemish'),
    ('dz', 'Dzongkha'),
    ('el', 'Greek, Modern (1453-)'),
    ('en', 'English'),
    ('eo', 'Esperanto'),
    ('et', 'Estonian'),
    ('eu', 'Basque'),
    ('ee', 'Ewe'),
    ('fo', 'Faroese'),
    ('fa', 'Persian'),
    ('fj', 'Fijian'),
    ('fi', 'Finnish'),
    ('fr', 'French'),
    ('fy', 'Western Frisian'),
    ('ff', 'Fulah'),
    ('Ga', 'Georgian'),
    ('de', 'German'),
    ('gd', 'Gaelic; Scottish Gaelic'),
    ('ga', 'Irish'),
    ('gl', 'Galician'),
    ('gv', 'Manx'),
    ('el', 'Greek, Modern (1453-)'),
    ('gn', 'Guarani'),
    ('gu', 'Gujarati'),
    ('ht', 'Haitian; Haitian Creole'),
    ('ha', 'Hausa'),
    ('he', 'Hebrew'),
    ('hz', 'Herero'),
    ('hi', 'Hindi'),
    ('ho', 'Hiri Motu'),
    ('hr', 'Croatian'),
    ('hu', 'Hungarian'),
    ('hy', 'Armenian'),
    ('ig', 'Igbo'),
    ('is', 'Icelandic'),
    ('io', 'Ido'),
    ('ii', 'Sichuan Yi; Nuosu'),
    ('iu', 'Inuktitut'),
    ('ie', 'Interlingue; Occidental'),
    ('ia', 'Interlingua (International Auxiliary Language Association)'),
    ('id', 'Indonesian'),
    ('ik', 'Inupiaq'),
    ('is', 'Icelandic'),
    ('it', 'Italian'),
    ('jv', 'Javanese'),
    ('ja', 'Japanese'),
    ('kl', 'Kalaallisut; Greenlandic'),
    ('kn', 'Kannada'),
    ('ks', 'Kashmiri'),
    ('ka', 'Georgian'),
    ('kr', 'Kanuri'),
    ('kk', 'Kazakh'),
    ('km', 'Central Khmer'),
    ('ki', 'Kikuyu; Gikuyu'),
    ('rw', 'Kinyarwanda'),
    ('ky', 'Kirghiz; Kyrgyz'),
    ('kv', 'Komi'),
    ('kg', 'Kongo'),
    ('ko', 'Korean'),
    ('kj', 'Kuanyama; Kwanyama'),
    ('ku', 'Kurdish'),
    ('lo', 'Lao'),
    ('la', 'Latin'),
    ('lv', 'Latvian'),
    ('li', 'Limburgan; Limburger; Limburgish'),
    ('ln', 'Lingala'),
    ('lt', 'Lithuanian'),
    ('lb', 'Luxembourgish; Letzeburgesch'),
    ('lu', 'Luba-Katanga'),
    ('lg', 'Ganda'),
    ('mk', 'Macedonian'),
    ('mh', 'Marshallese'),
    ('ml', 'Malayalam'),
    ('mi', 'Maori'),
    ('mr', 'Marathi'),
    ('ms', 'Malay'),
    ('Mi', 'Micmac'),
    ('mk', 'Macedonian'),
    ('mg', 'Malagasy'),
    ('mt', 'Maltese'),
    ('mn', 'Mongolian'),
    ('mi', 'Maori'),
    ('ms', 'Malay'),
    ('my', 'Burmese'),
    ('na', 'Nauru'),
    ('nv', 'Navajo; Navaho'),
    ('nr', 'Ndebele, South; South Ndebele'),
    ('nd', 'Ndebele, North; North Ndebele'),
    ('ng', 'Ndonga'),
    ('ne', 'Nepali'),
    ('nl', 'Dutch; Flemish'),
    ('nn', 'Norwegian Nynorsk; Nynorsk, Norwegian'),
    ('nb', 'Bokmål, Norwegian; Norwegian Bokmål'),
    ('no', 'Norwegian'),
    ('oc', 'Occitan (post 1500)'),
    ('oj', 'Ojibwa'),
    ('or', 'Oriya'),
    ('om', 'Oromo'),
    ('os', 'Ossetian; Ossetic'),
    ('pa', 'Panjabi; Punjabi'),
    ('fa', 'Persian'),
    ('pi', 'Pali'),
    ('pl', 'Polish'),
    ('pt', 'Portuguese'),
    ('ps', 'Pushto; Pashto'),
    ('qu', 'Quechua'),
    ('rm', 'Romansh'),
    ('ro', 'Romanian; Moldavian; Moldovan'),
    ('ro', 'Romanian; Moldavian; Moldovan'),
    ('rn', 'Rundi'),
    ('ru', 'Russian'),
    ('sg', 'Sango'),
    ('sa', 'Sanskrit'),
    ('si', 'Sinhala; Sinhalese'),
    ('sk', 'Slovak'),
    ('sk', 'Slovak'),
    ('sl', 'Slovenian'),
    ('se', 'Northern Sami'),
    ('sm', 'Samoan'),
    ('sn', 'Shona'),
    ('sd', 'Sindhi'),
    ('so', 'Somali'),
    ('st', 'Sotho, Southern'),
    ('es', 'Spanish; Castilian'),
    ('sq', 'Albanian'),
    ('sc', 'Sardinian'),
    ('sr', 'Serbian'),
    ('ss', 'Swati'),
    ('su', 'Sundanese'),
    ('sw', 'Swahili'),
    ('sv', 'Swedish'),
    ('ty', 'Tahitian'),
    ('ta', 'Tamil'),
    ('tt', 'Tatar'),
    ('te', 'Telugu'),
    ('tg', 'Tajik'),
    ('tl', 'Tagalog'),
    ('th', 'Thai'),
    ('bo', 'Tibetan'),
    ('ti', 'Tigrinya'),
    ('to', 'Tonga (Tonga Islands)'),
    ('tn', 'Tswana'),
    ('ts', 'Tsonga'),
    ('tk', 'Turkmen'),
    ('tr', 'Turkish'),
    ('tw', 'Twi'),
    ('ug', 'Uighur; Uyghur'),
    ('uk', 'Ukrainian'),
    ('ur', 'Urdu'),
    ('uz', 'Uzbek'),
    ('ve', 'Venda'),
    ('vi', 'Vietnamese'),
    ('vo', 'Volapük'),
    ('cy', 'Welsh'),
    ('wa', 'Walloon'),
    ('wo', 'Wolof'),
    ('xh', 'Xhosa'),
    ('yi', 'Yiddish'),
    ('yo', 'Yoruba'),
    ('za', 'Zhuang; Chuang'),
    ('zh', 'Chinese'),
    ('zu', 'Zulu')
]

countries = [
    ('AF', u'Afghanistan'),
    ('AX', u'\xc5land Islands'),
    ('AL', u'Albania'),
    ('DZ', u'Algeria'),
    ('AS', u'American Samoa'),
    ('AD', u'Andorra'),
    ('AO', u'Angola'),
    ('AI', u'Anguilla'),
    ('AQ', u'Antarctica'),
    ('AG', u'Antigua and Barbuda'),
    ('AR', u'Argentina'),
    ('AM', u'Armenia'),
    ('AW', u'Aruba'),
    ('AU', u'Australia'),
    ('AT', u'Austria'),
    ('AZ', u'Azerbaijan'),
    ('BS', u'Bahamas'),
    ('BH', u'Bahrain'),
    ('BD', u'Bangladesh'),
    ('BB', u'Barbados'),
    ('BY', u'Belarus'),
    ('BE', u'Belgium'),
    ('BZ', u'Belize'),
    ('BJ', u'Benin'),
    ('BM', u'Bermuda'),
    ('BT', u'Bhutan'),
    ('BO', u'Bolivia, Plurinational State of'),
    ('BQ', u'Bonaire, Sint Eustatius and Saba'),
    ('BA', u'Bosnia and Herzegovina'),
    ('BW', u'Botswana'),
    ('BV', u'Bouvet Island'),
    ('BR', u'Brazil'),
    ('IO', u'British Indian Ocean Territory'),
    ('BN', u'Brunei Darussalam'),
    ('BG', u'Bulgaria'),
    ('BF', u'Burkina Faso'),
    ('BI', u'Burundi'),
    ('KH', u'Cambodia'),
    ('CM', u'Cameroon'),
    ('CA', u'Canada'),
    ('CV', u'Cape Verde'),
    ('KY', u'Cayman Islands'),
    ('CF', u'Central African Republic'),
    ('TD', u'Chad'),
    ('CL', u'Chile'),
    ('CN', u'China'),
    ('CX', u'Christmas Island'),
    ('CC', u'Cocos (Keeling Islands)'),
    ('CO', u'Colombia'),
    ('KM', u'Comoros'),
    ('CG', u'Congo'),
    ('CD', u'Congo, The Democratic Republic of the'),
    ('CK', u'Cook Islands'),
    ('CR', u'Costa Rica'),
    ('CI', u"C\xf4te D'ivoire"),
    ('HR', u'Croatia'),
    ('CU', u'Cuba'),
    ('CW', u'Cura\xe7ao'),
    ('CY', u'Cyprus'),
    ('CZ', u'Czech Republic'),
    ('DK', u'Denmark'),
    ('DJ', u'Djibouti'),
    ('DM', u'Dominica'),
    ('DO', u'Dominican Republic'),
    ('EC', u'Ecuador'),
    ('EG', u'Egypt'),
    ('SV', u'El Salvador'),
    ('GQ', u'Equatorial Guinea'),
    ('ER', u'Eritrea'),
    ('EE', u'Estonia'),
    ('ET', u'Ethiopia'),
    ('FK', u'Falkland Islands (Malvinas)'),
    ('FO', u'Faroe Islands'),
    ('FJ', u'Fiji'),
    ('FI', u'Finland'),
    ('FR', u'France'),
    ('GF', u'French Guiana'),
    ('PF', u'French Polynesia'),
    ('TF', u'French Southern Territories'),
    ('GA', u'Gabon'),
    ('GM', u'Gambia'),
    ('GE', u'Georgia'),
    ('DE', u'Germany'),
    ('GH', u'Ghana'),
    ('GI', u'Gibraltar'),
    ('GR', u'Greece'),
    ('GL', u'Greenland'),
    ('GD', u'Grenada'),
    ('GP', u'Guadeloupe'),
    ('GU', u'Guam'),
    ('GT', u'Guatemala'),
    ('GG', u'Guernsey'),
    ('GN', u'Guinea'),
    ('GW', u'Guinea-bissau'),
    ('GY', u'Guyana'),
    ('HT', u'Haiti'),
    ('HM', u'Heard Island and McDonald Islands'),
    ('VA', u'Holy See (Vatican City State)'),
    ('HN', u'Honduras'),
    ('HK', u'Hong Kong'),
    ('HU', u'Hungary'),
    ('IS', u'Iceland'),
    ('IN', u'India'),
    ('ID', u'Indonesia'),
    ('IR', u'Iran, Islamic Republic of'),
    ('IQ', u'Iraq'),
    ('IE', u'Ireland'),
    ('IM', u'Isle of Man'),
    ('IL', u'Israel'),
    ('IT', u'Italy'),
    ('JM', u'Jamaica'),
    ('JP', u'Japan'),
    ('JE', u'Jersey'),
    ('JO', u'Jordan'),
    ('KZ', u'Kazakhstan'),
    ('KE', u'Kenya'),
    ('KI', u'Kiribati'),
    ('KP', u"Korea, Democratic People's Republic of"),
    ('KR', u'Korea, Republic of'),
    ('KW', u'Kuwait'),
    ('KG', u'Kyrgyzstan'),
    ('LA', u"Lao People's Democratic Republic"),
    ('LV', u'Latvia'),
    ('LB', u'Lebanon'),
    ('LS', u'Lesotho'),
    ('LR', u'Liberia'),
    ('LY', u'Libya'),
    ('LI', u'Liechtenstein'),
    ('LT', u'Lithuania'),
    ('LU', u'Luxembourg'),
    ('MO', u'Macao'),
    ('MK', u'Macedonia, The Former Yugoslav Republic of'),
    ('MG', u'Madagascar'),
    ('MW', u'Malawi'),
    ('MY', u'Malaysia'),
    ('MV', u'Maldives'),
    ('ML', u'Mali'),
    ('MT', u'Malta'),
    ('MH', u'Marshall Islands'),
    ('MQ', u'Martinique'),
    ('MR', u'Mauritania'),
    ('MU', u'Mauritius'),
    ('YT', u'Mayotte'),
    ('MX', u'Mexico'),
    ('FM', u'Micronesia, Federated States of'),
    ('MD', u'Moldova, Republic of'),
    ('MC', u'Monaco'),
    ('MN', u'Mongolia'),
    ('ME', u'Montenegro'),
    ('MS', u'Montserrat'),
    ('MA', u'Morocco'),
    ('MZ', u'Mozambique'),
    ('MM', u'Myanmar'),
    ('NA', u'Namibia'),
    ('NR', u'Nauru'),
    ('NP', u'Nepal'),
    ('NL', u'Netherlands'),
    ('NC', u'New Caledonia'),
    ('NZ', u'New Zealand'),
    ('NI', u'Nicaragua'),
    ('NE', u'Niger'),
    ('NG', u'Nigeria'),
    ('NU', u'Niue'),
    ('NF', u'Norfolk Island'),
    ('MP', u'Northern Mariana Islands'),
    ('NO', u'Norway'),
    ('OM', u'Oman'),
    ('PK', u'Pakistan'),
    ('PW', u'Palau'),
    ('PS', u'Palestinian Territory, Occupied'),
    ('PA', u'Panama'),
    ('PG', u'Papua New Guinea'),
    ('PY', u'Paraguay'),
    ('PE', u'Peru'),
    ('PH', u'Philippines'),
    ('PN', u'Pitcairn'),
    ('PL', u'Poland'),
    ('PT', u'Portugal'),
    ('PR', u'Puerto Rico'),
    ('QA', u'Qatar'),
    ('RE', u'R\xe9union'),
    ('RO', u'Romania'),
    ('RU', u'Russian Federation'),
    ('RW', u'Rwanda'),
    ('BL', u'Saint Barth\xe9lemy'),
    ('SH', u'Saint Helena, Ascension and Tristan Da Cunha'),
    ('KN', u'Saint Kitts and Nevis'),
    ('LC', u'Saint Lucia'),
    ('MF', u'Saint Martin (French Part)'),
    ('PM', u'Saint Pierre and Miquelon'),
    ('VC', u'Saint Vincent and the Grenadines'),
    ('WS', u'Samoa'),
    ('SM', u'San Marino'),
    ('ST', u'Sao Tome and Principe'),
    ('SA', u'Saudi Arabia'),
    ('SN', u'Senegal'),
    ('RS', u'Serbia'),
    ('SC', u'Seychelles'),
    ('SL', u'Sierra Leone'),
    ('SG', u'Singapore'),
    ('SX', u'Sint Maarten (Dutch Part)'),
    ('SK', u'Slovakia'),
    ('SI', u'Slovenia'),
    ('SB', u'Solomon Islands'),
    ('SO', u'Somalia'),
    ('ZA', u'South Africa'),
    ('GS', u'South Georgia and the South Sandwich Islands'),
    ('SS', u'South Sudan'),
    ('ES', u'Spain'),
    ('LK', u'Sri Lanka'),
    ('SD', u'Sudan'),
    ('SR', u'Suriname'),
    ('SJ', u'Svalbard and Jan Mayen'),
    ('SZ', u'Swaziland'),
    ('SE', u'Sweden'),
    ('CH', u'Switzerland'),
    ('SY', u'Syrian Arab Republic'),
    ('TW', u'Taiwan, Province of China'),
    ('TJ', u'Tajikistan'),
    ('TZ', u'Tanzania, United Republic of'),
    ('TH', u'Thailand'),
    ('TL', u'Timor-leste'),
    ('TG', u'Togo'),
    ('TK', u'Tokelau'),
    ('TO', u'Tonga'),
    ('TT', u'Trinidad and Tobago'),
    ('TN', u'Tunisia'),
    ('TR', u'Turkey'),
    ('TM', u'Turkmenistan'),
    ('TC', u'Turks and Caicos Islands'),
    ('TV', u'Tuvalu'),
    ('UG', u'Uganda'),
    ('UA', u'Ukraine'),
    ('AE', u'United Arab Emirates'),
    ('GB', u'United Kingdom'),
    ('US', u'United States'),
    ('UM', u'United States Minor Outlying Islands'),
    ('UY', u'Uruguay'),
    ('UZ', u'Uzbekistan'),
    ('VU', u'Vanuatu'),
    ('VE', u'Venezuela, Bolivarian Republic of'),
    ('VN', u'Viet Nam'),
    ('VG', u'Virgin Islands, British'),
    ('VI', u'Virgin Islands, U.S.'),
    ('WF', u'Wallis and Futuna'),
    ('EH', u'Western Sahara'),
    ('YE', u'Yemen'),
    ('ZM', u'Zambia'),
    ('ZW', u'Zimbabwe')
]
professors = [
    ("Monika Abramenko", "Monika Abramenko"),
    ("Scott T. Acton", "Scott T. Acton"),
    ("Sean R. Agnew", "Sean R. Agnew"),
    ("Negin Alemazkoor", "Negin Alemazkoor"),
    ("Homa Alemzadeh", "Homa Alemzadeh"),
    ("Timothy E. Allen", "Timothy E. Allen"),
    ("Eric Anderson", "Eric Anderson"),
    ("Panagiotis Apostolellis", "Panagiotis Apostolellis"),
    ("Robert Archer", "Robert Archer"),
    ("Robert Reid Bailey", "Robert Reid Bailey"),
    ("Prasanna Venkata Balachandran", "Prasanna Venkata Balachandran"),
    ("Catherine Baritaud", "Catherine Baritaud"),
    ("Nicolas S. Barker", "Nicolas S. Barker"),
    ("Shannon Barker", "Shannon Barker"),
    ("Thomas H. Barker", "Thomas H. Barker"),
    ("Adam Barnes", "Adam Barnes"),
    ("Laura Barnes", "Laura Barnes"),
    ("Christopher Barrett", "Christopher Barrett"),
    ("Hilary Bart-Smith", "Hilary Bart-Smith"),
    ("Nada Basit", "Nada Basit"),
    ("Madhur Behl", "Madhur Behl"),
    ("Peter A. Beling", "Peter A. Beling"),
    ("Andreas Beling", "Andreas Beling"),
    ("Craig H. Benson", "Craig H. Benson"),
    ("Bryan W. Berger", "Bryan W. Berger"),
    ("Rosalyn W. Berne", "Rosalyn W. Berne"),
    ("Nicola Bezzo", "Nicola Bezzo"),
    ("Charles Blankenship", "Charles Blankenship"),
    ("Silvia S. Blemker", "Silvia S. Blemker"),
    ("Aaron Bloomfield", "Aaron Bloomfield"),
    ("Mehdi Boukhechba", "Mehdi Boukhechba"),
    ("Steven Michael Bowers", "Steven Michael Bowers"),
    ("Donald E. Brown", "Donald E. Brown"),
    ("Nathan J. Brunelle", "Nathan J. Brunelle"),
    ("Lindsay Burden", "Lindsay Burden"),
    ("James T. Burns", "James T. Burns"),
    ("Liheng Cai", "Liheng Cai"),
    ("Benton H. Calhoun", "Benton H. Calhoun"),
    ("Steven Richard Caliari", "Steven Richard Caliari"),
    ("Joe C. Campbell", "Joe C. Campbell"),
    ("Bradford J. Campbell", "Bradford J. Campbell"),
    ("W Carlson", "W Carlson"),
    ("Giorgio Carta", "Giorgio Carta"),
    ("Qing Chang", "Qing Chang"),
    ("Harsha K. Chelliah", "Harsha K. Chelliah"),
    ("Tong Donna Chen", "Tong Donna Chen"),
    ("Joshua J. Choi", "Joshua J. Choi"),
    ("George Joseph Christ", "George Joseph Christ"),
    ("Andres F. Clarens", "Andres F. Clarens"),
    ("James P. Cohoon", "James P. Cohoon"),
    ("/238 RESULTS", "/238 RESULTS"),
    ("Teresa B. Culver", "Teresa B. Culver"),
    ("Jack W. Davidson", "Jack W. Davidson"),
    ("Robert J. Davis", "Robert J. Davis"),
    ("Chloe Dedic", "Chloe Dedic"),
    ("Todd A DeLong", "Todd A DeLong"),
    ("Craig Dill", "Craig Dill"),
    ("Haibo Dong", "Haibo Dong"),
    ("Afsaneh Doryab", "Afsaneh Doryab"),
    ("Joanne B. Dugan", "Joanne B. Dugan"),
    ("Matthew Dwyer", "Matthew Dwyer"),
    ("Sebastian Elbaum", "Sebastian Elbaum"),
    ("Dana M. Elzey", "Dana M. Elzey"),
    ("William S. Epling", "William S. Epling"),
    ("Keivan Esfarjani", "Keivan Esfarjani"),
    ("David Evans", "David Evans"),
    ("Lu Feng", "Lu Feng"),
    ("Sean Ferguson", "Sean Ferguson"),
    ("Roger L. Fittro", "Roger L. Fittro"),
    ("James M. Fitz-Gerald", "James M. Fitz-Gerald"),
    ("Preston Fletcher", "Preston Fletcher"),
    ("Jerrold A. Floro", "Jerrold A. Floro"),
    ("Mark Richard Floryan", "Mark Richard Floryan"),
    ("Rider W. Foley", "Rider W. Foley"),
    ("Roseanne Ford", "Roseanne Ford"),
    ("Diana Franco Duran", "Diana Franco Duran"),
    ("Bernard Fulgham", "Bernard Fulgham"),
    ("Tomonari Furukawa", "Tomonari Furukawa"),
    ("Gavin T. Garner", "Gavin T. Garner"),
    ("Geoffrey Matthew Geise", "Geoffrey Matthew Geise"),
    ("Gregory J. Gerling", "Gregory J. Gerling"),
    ("Avik Ghosh", "Avik Ghosh"),
    ("Gaurav Giri", "Gaurav Giri"),
    ("Jonathan L Goodall", "Jonathan L Goodall"),
    ("Michael E. Gorman", "Michael E. Gorman"),
    ("Christopher P. Goyne", "Christopher P. Goyne"),
    ("Daniel Graham", "Daniel Graham"),
    ("David L. Green", "David L. Green"),
    ("Donald Richieri Griffin", "Donald Richieri Griffin"),
    ("Andrew S. Grimshaw", "Andrew S. Grimshaw"),
    ("James F. Groves", "James F. Groves"),
    ("Gianluca Guadagni", "Gianluca Guadagni"),
    ("William H. Guilford", "William H. Guilford"),
    ("Mool C. Gupta", "Mool C. Gupta"),
    ("757-766-4608", "757-766-4608"),
    ("Devin K. Harris", "Devin K. Harris"),
    ("Farzad Farnoud Hassanzadeh", "Farzad Farnoud Hassanzadeh"),
    ("Christian Hellings", "Christian Hellings"),
    ("Brian P. Helmke", "Brian P. Helmke"),
    ("Seongkook Heo", "Seongkook Heo"),
    ("Arsalan Heydarian", "Arsalan Heydarian"),
    ("Chris Highley", "Chris Highley"),
    ("Jeffrey W. Holmes", "Jeffrey W. Holmes"),
    ("Patrick E. Hopkins", "Patrick E. Hopkins"),
    ("Barry Horowitz", "Barry Horowitz"),
    ("Thomas B. Horton", "Thomas B. Horton"),
    ("John A. Hossack", "John A. Hossack"),
    ("John Hott", "John Hott"),
    ("James M. Howe", "James M. Howe"),
    ("Marty A. Humphrey", "Marty A. Humphrey"),
    ("Jon Fredrick Ihlefeld", "Jon Fredrick Ihlefeld"),
    ("Tariq Iqbal", "Tariq Iqbal"),
    ("Kevin A. Janes", "Kevin A. Janes"),
    ("Yangfeng Ji", "Yangfeng Ji"),
    ("Barry W. Johnson", "Barry W. Johnson"),
    ("Robert G. Kelly", "Robert G. Kelly"),
    ("Richard Kent", "Richard Kent"),
    ("Jason R. Kerrigan", "Jason R. Kerrigan"),
    ("Samira Manabi Khan", "Samira Manabi Khan"),
    ("Leidy Klotz", "Leidy Klotz"),
    ("Carl R. Knospe", "Carl R. Knospe"),
    ("Gary M. Koenig", "Gary M. Koenig"),
    ("Anne Kromkowski", "Anne Kromkowski"),
    ("Roman Krzysztofowicz", "Roman Krzysztofowicz"),
    ("Tsai-Hsuan Tsai-Hsuan Ku", "Tsai-Hsuan Tsai-Hsuan Ku"),
    ("Yonghwi Kwon", "Yonghwi Kwon"),
    ("Venkataraman Lakshmi", "Venkataraman Lakshmi"),
    ("James H. Lambert", "James H. Lambert"),
    ("Kyle J. Lampe", "Kyle J. Lampe"),
    ("James Lark", "James Lark"),
    ("Benjamin Laugelli", "Benjamin Laugelli"),
    ("Matthew J. Lazzara", "Matthew J. Lazzara"),
    ("Kyusang Lee", "Kyusang Lee"),
    ("Rachel A Letteri", "Rachel A Letteri"),
    ("Xiaodong Li", "Xiaodong Li"),
    ("Meiqin Li", "Meiqin Li"),
    ("Jundong Li", "Jundong Li"),
    ("Arthur W. Lichtenberger", "Arthur W. Lichtenberger"),
    ("Zongli Lin", "Zongli Lin"),
    ("Xiaozhu Lin", "Xiaozhu Lin"),
    ("Eric Loth", "Eric Loth"),
    ("Garrick E. Louis", "Garrick E. Louis"),
    ("Lin Ma", "Lin Ma"),
    ("Hui Ma", "Hui Ma"),
    ("Ji Ma", "Ji Ma"),
    ("Mohammad Mahmoody Ghidary", "Mohammad Mahmoody Ghidary"),
    ("Deepyaman Maiti", "Deepyaman Maiti"),
    ("Worthy N. Martin", "Worthy N. Martin"),
    ("Richard Martukanitz", "Richard Martukanitz"),
    ("Frank William Mauldin", "Frank William Mauldin"),
    ("Frances McBride", "Frances McBride"),
    ("Paul McBurney", "Paul McBurney"),
    ("Stephen John McDonnell", "Stephen John McDonnell"),
    ("Manouchehr Mohajeri", "Manouchehr Mohajeri"),
    ("Michael Momot", "Michael Momot"),
    ("Diana Morris", "Diana Morris"),
    ("Henning Mortveit", "Henning Mortveit"),
    ("Kristen Naegle", "Kristen Naegle"),
    ("Kathryn A. Neeley", "Kathryn A. Neeley"),
    ("Nhat Nguyen", "Nhat Nguyen"),
    ("Pamela M. Norris", "Pamela M. Norris"),
    ("Peter D. Norton", "Peter D. Norton"),
    ("Toluwalogo Odumosu", "Toluwalogo Odumosu"),
    ("Elizabeth J. Opila", "Elizabeth J. Opila"),
    ("Vicente Ordonez-Roman", "Vicente Ordonez-Roman"),
    ("Elizabeth Orrico", "Elizabeth Orrico"),
    ("Osman E. Ozbulut", "Osman E. Ozbulut"),
    ("Matthew B. Panzer", "Matthew B. Panzer"),
    ("Chris Paolucci", "Chris Paolucci"),
    ("B. Brian Park", "B. Brian Park"),
    ("Lisa Colosi Peterson", "Lisa Colosi Peterson"),
    ("Raymond S Pettit", "Raymond S Pettit"),
    ("Marek-Jerzy Pindera", "Marek-Jerzy Pindera"),
    ("Stacie Pisano", "Stacie Pisano"),
    ("Michael D Porter", "Michael D Porter"),
    ("Harry C. Powell", "Harry C. Powell"),
    ("Upsorn Praphamontripong", "Upsorn Praphamontripong"),
    ("Richard J. Price", "Richard J. Price"),
    ("George Prpich", "George Prpich"),
    ("Yanjun Qi", "Yanjun Qi"),
    ("Daniel Benjamin Quinn", "Daniel Benjamin Quinn"),
    ("Julianne Dorothy Quinn", "Julianne Dorothy Quinn"),
    ("Ann Reimers", "Ann Reimers"),
    ("Petra Reinke", "Petra Reinke"),
    ("Charles Reiss", "Charles Reiss"),
    ("Sara Riggs", "Sara Riggs"),
    ("Robert Riggs", "Robert Riggs"),
    ("Gustavo Kunde Rohde", "Gustavo Kunde Rohde"),
    ("Mitchel C. Rosen", "Mitchel C. Rosen"),
    ("Jonathan Rosen", "Jonathan Rosen"),
    ("Megan Ryals", "Megan Ryals"),
    ("Robert S. Salzar", "Robert S. Salzar"),
    ("William T. Scherer", "William T. Scherer"),
    ("John R. Scully", "John R. Scully"),
    ("Bryn Elizabeth Seabrook", "Bryn Elizabeth Seabrook"),
    ("Majid Shafiee-Jood", "Majid Shafiee-Jood"),
    ("Cong Shen", "Cong Shen"),
    ("Haiying Shen", "Haiying Shen"),
    ("Mark S. Sherriff", "Mark S. Sherriff"),
    ("Nikhil Shukla", "Nikhil Shukla"),
    ("Nikolaos D. Sidiropoulos", "Nikolaos D. Sidiropoulos"),
    ("Kevin Skadron", "Kevin Skadron"),
    ("David L. Slutzky", "David L. Slutzky"),
    ("Mary Smith", "Mary Smith"),
    ("Natasha Leigh Smith", "Natasha Leigh Smith"),
    ("James A. Smith", "James A. Smith"),
    ("Brian L. Smith", "Brian L. Smith"),
    ("Mary Lou Soffa", "Mary Lou Soffa"),
    ("Julia Spencer", "Julia Spencer"),
    ("Mircea R. Stan", "Mircea R. Stan"),
    ("John A Stankovic", "John A Stankovic"),
    ("Kevin J. Sullivan", "Kevin J. Sullivan"),
    ("Yixin Sun", "Yixin Sun"),
    ("Tao Sun", "Tao Sun"),
    ("Nathan Swami", "Nathan Swami"),
    ("Gang Tao", "Gang Tao"),
    ("Yuan Tian", "Yuan Tian"),
    ("Luther A. Tychonievich", "Luther A. Tychonievich"),
    ("Ronald Unnerstall", "Ronald Unnerstall"),
    ("Ashish Venkat", "Ashish Venkat"),
    ("Haydn N. Wadley", "Haydn N. Wadley"),
    ("Hongning Wang", "Hongning Wang"),
    ("Robert M. Weikle", "Robert M. Weikle"),
    ("Daniel S. Weller", "Daniel S. Weller"),
    ("Cameron Whitehouse", "Cameron Whitehouse"),
    ("Keith A. Williams", "Keith A. Williams"),
    ("Ronald D. Williams", "Ronald D. Williams"),
    ("Houston G Wood", "Houston G Wood"),
    ("David Wu", "David Wu"),
    ("Caitlin Donahue Wylie", "Caitlin Donahue Wylie"),
    ("Baoxing Xu", "Baoxing Xu"),
    ("Haifeng Xu", "Haifeng Xu"),
    ("Xu Yi", "Xu Yi"),
    ("Giovanni Zangari", "Giovanni Zangari"),
    ("Mona Zebarjadi", "Mona Zebarjadi"),
    ("Miaomiao Zhang", "Miaomiao Zhang"),
    ("Aidong Zhang", "Aidong Zhang"),
    ("Leonid V. Zhigilei", "Leonid V. Zhigilei"),
    ("Bicheng Zhou", "Bicheng Zhou"),
    ("Eli R Zunder", "Eli R Zunder")
]


Timezone = (
    ('ANAT', "Anadyr"),
    ('AEDT', "Melbourne"),
    ('AEST', "Brisbane"),
    ('JST', "Tokyo"),
    ('CST', "Beijing"),
    ('WIB', "Jakarta"),
    ('UZT', "Tashkent"),
    ('GST', "Dubai"),
    ('MSK', "Moscow"),
    ('CEST', "Brussels"),
    ('BST', "London"),
    ('GMT', "Accra"),
    ('CVT', "Praia"),
    ('WGST', "Nuuk"),
    ('ART', "Buenos Aires"),
    ('EDT', "New York"),
    ('CDT', "Mexico City"),
    ('PDT', "Los Angeles"),
    ('AKDT', "Anchorage"),
    ('HDT', "Adak"),
    ('HST', "Honolulu"),
    ('NUT', "Alofi"),
    ('AoE', "Baker Island"),
    ('LINT', "Kiritimati"),
    ('NZDT', "Auckland"),
    ('ACDT', "Adelaide"),
    ('ACST', "Darwin"),
    ('MMT', "Yangon"),
    ('IST', "New Delhi"),
    ('AFT', "Kabul"),
    ('IRST', "Tehran"),
    ('NDT', "St. John's"),
    ('MART', "Taiohae"),
    ('CHADT', "Chatham Islands"),
    ('ACWST', "Eucla"),
    ('NPT', "Kathmandu")
)
Course = (
    ('APMA', "APMA"),
    ('BME', "BME"),
    ('CS', "CS"),
    ('CE', "CE"),
    ('CHE', "CHE"),
    ('CPE', "CPE"),
    ('ECE', "ECE"),
    ('MAE', "MAE"),
    ('STS', "STS")
)

Lecture = (
    ('WEB_BASED', "WEB_BASED"),
    ('IN_PERSON', "IN_PERSON")
)


majors = [
    ('African American & African Studies', 'African American & African Studies'),
    ('American Studies', 'American Studies'),
    ('Anthropology', 'Anthropology'),
    ('Art History', 'Art History'),
    ('Art, Studio', 'Art, Studio'),
    ('Astronomy', 'Astronomy'),
    ('Astronomy-Physics', 'Astronomy-Physics'),
    ('Biology', 'Biology'),
    ('Chemistry', 'Chemistry'),
    ('Chinese Language & Literature', 'Chinese Language & Literature'),
    ('Classics', 'Classics'),
    ('Cognitive Science', 'Cognitive Science'),
    ('Comparative Literature', 'Comparative Literature'),
    ('Computer Science', 'Computer Science'),
    ('Drama', 'Drama'),
    ('East Asian Studies', 'East Asian Studies'),
    ('Economics', 'Economics'),
    ('English', 'English'),
    ('Environmental Sciences', 'Environmental Sciences'),
    ('Environmental Thought & Practice', 'Environmental Thought & Practice'),
    ('French', 'French'),
    ('German', 'German'),
    ('Global Studies', 'Global Studies'),
    ('History', 'History'),
    ('Human Biology', 'Human Biology'),
    ('Italian', 'Italian'),
    ('Japanese Language & Literature', 'Japanese Language & Literature'),
    ('Jewish Studies', 'Jewish Studies'),
    ('Latin American Studies', 'Latin American Studies'),
    ('Linguistics', 'Linguistics'),
    ('Mathematics', 'Mathematics'),
    ('Media Studies', 'Media Studies'),
    ('Medieval Studies', 'Medieval Studies'),
    ('Middle Eastern and South Asian Languages and Cultures', 'Middle Eastern and South Asian Languages and Cultures'),
    ('Music', 'Music'),
    ('Neuroscience', 'Neuroscience'),
    ('Philosophy', 'Philosophy'),
    ('Physics', 'Physics'),
    ('Political and Social Thought', 'Political and Social Thought'),
    ('Political Philosophy, Policy, and Law', 'Political Philosophy, Policy, and Law'),
    ('Politics', 'Politics'),
    ('Psychology', 'Psychology'),
    ('Religious Studies', 'Religious Studies'),
    ('Slavic Languages and Literatures', 'Slavic Languages and Literatures'),
    ('Sociology', 'Sociology'),
    ('South Asian Studies', 'South Asian Studies'),
    ('Spanish', 'Spanish'),
    ('Statistics', 'Statistics'),
    ('Women, Gender, and Sexuality', 'Women, Gender, and Sexuality'),
    ('Aerospace Engineering', 'Aerospace Engineering'),
    ('Biomedical Engineering', 'Biomedical Engineering'),
    ('Chemical Engineering', 'Chemical Engineering'),
    ('Civil Engineering', 'Civil Engineering'),
    ('Computer Engineering', 'Computer Engineering'),
    ('Computer Science', 'Computer Science'),
    ('Electrical Engineering', 'Electrical Engineering'),
    ('Engineering Science', 'Engineering Science'),
    ('Mechanical Engineering', 'Mechanical Engineering'),
    ('Systems Engineering', 'Systems Engineering'),
    ('Accounting', 'Accounting'),
    ('Finance', 'Finance'),
    ('Information Technology', 'Information Technology'),
    ('Management', 'Management'),
    ('Marketing', 'Marketing'),
    ('School of Architecture', 'School of Architecture'),
    ('Architectural History', 'Architectural History'),
    ('Architecture', 'Architecture'),
    ('Urban & Environmental Planning', 'Urban & Environmental Planning'),
    ('School of Nursing', 'School of Nursing'),
    ('Bachelor of Science in Nursing (BSN)', 'Bachelor of Science in Nursing (BSN)'),
    ('RN to BSN', 'RN to BSN'),
    ('Batten School of Leadership and Public Policy', 'Batten School of Leadership and Public Policy'),
    ('B.A. in Public Policy and Leadership', 'B.A. in Public Policy and Leadership'),
    ('Accelerated B.A./Master of Public Policy (MPP) Program', 'Accelerated B.A./Master of Public Policy (MPP) Program'),
    ('Curry School of Education', 'Curry School of Education'),
    ('Kinesiology', 'Kinesiology'),
    ('Speech Communications Disorders', 'Speech Communications Disorders'),
    ('Youth & Social Innovation', 'Youth & Social Innovation'),
    ('Teacher Education majors (B.S.Ed.)', 'Teacher Education majors (B.S.Ed.)'),
    ('Early Childhood Education', 'Early Childhood Education'),
    ('Elementary Education', 'Elementary Education'),
    ('Special Education', 'Special Education'),
    ('Teacher Education (listing-graduate Master of Teaching)',
     'Teacher Education (listing-graduate Master of Teaching)'),
    ('Elementary Education', 'Elementary Education'),
    ('English Education', 'English Education'),
    ('English as a Second Language Education', 'English as a Second Language Education'),
    ('Foreign Language Education', 'Foreign Language Education'),
    ('Mathematics Education', 'Mathematics Education'),
    ('Science Education', 'Science Education'),
    ('Social Studies Education', 'Social Studies Education'),
    ('Special Education', 'Special Education')
]
#
# majors = (
#     ('cs', 'Computer Science'),
#     ('other', 'non-CS major')
# )

years = (
    ('2020', '2020'),
    ('2021', '2021'),
    ('2022', '2022'),
    ('2023', '2023'),
    ('2024', '2024'),
    ('2025', '2025'),
    ('2026', '2026'),
    ('2027', '2027'),
)

uva_classes = (
    ('CS1111', 'CS1111'),
    ('CS2102', 'CS2102'),
    ('CS2110', 'CS2110'),
    ('CS2150', 'CS2150'),
    ('CS3240', 'CS3240'),
    ('lame class', 'lame class'),
)


group_members = (
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
)
