languages = [
    ('Afar', 'Afar'),
    ('Abkhazian', 'Abkhazian'),
    ('Afrikaans', 'Afrikaans'),
    ('Akan', 'Akan'),
    ('Albanian', 'Albanian'),
    ('Amharic', 'Amharic'),
    ('Arabic', 'Arabic'),
    ('Aragonese', 'Aragonese'),
    ('Armenian', 'Armenian'),
    ('Assamese', 'Assamese'),
    ('Avaric', 'Avaric'),
    ('Avestan', 'Avestan'),
    ('Aymara', 'Aymara'),
    ('Azerbaijani', 'Azerbaijani'),
    ('Bashkir', 'Bashkir'),
    ('Bambara', 'Bambara'),
    ('Basque', 'Basque'),
    ('Belarusian', 'Belarusian'),
    ('Bengali', 'Bengali'),
    ('Bihari languages', 'Bihari languages'),
    ('Bislama', 'Bislama'),
    ('Tibetan', 'Tibetan'),
    ('Bosnian', 'Bosnian'),
    ('Breton', 'Breton'),
    ('Bulgarian', 'Bulgarian'),
    ('Burmese', 'Burmese'),
    ('Catalan; Valencian', 'Catalan; Valencian'),
    ('Czech', 'Czech'),
    ('Chamorro', 'Chamorro'),
    ('Chechen', 'Chechen'),
    ('Chinese', 'Chinese'),
    ('Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic',
     'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
    ('Chuvash', 'Chuvash'),
    ('Cornish', 'Cornish'),
    ('Corsican', 'Corsican'),
    ('Cree', 'Cree'),
    ('Welsh', 'Welsh'),
    ('Czech', 'Czech'),
    ('Danish', 'Danish'),
    ('German', 'German'),
    ('Divehi; Dhivehi; Maldivian', 'Divehi; Dhivehi; Maldivian'),
    ('Dutch; Flemish', 'Dutch; Flemish'),
    ('Dzongkha', 'Dzongkha'),
    ('Greek, Modern (1453-', 'Greek, Modern (1453-)'),
    ('English', 'English'),
    ('Esperanto', 'Esperanto'),
    ('Estonian', 'Estonian'),
    ('Basque', 'Basque'),
    ('Ewe', 'Ewe'),
    ('Faroese', 'Faroese'),
    ('Persian', 'Persian'),
    ('Fijian', 'Fijian'),
    ('Finnish', 'Finnish'),
    ('French', 'French'),
    ('Western Frisian', 'Western Frisian'),
    ('Fulah', 'Fulah'),
    ('Georgian', 'Georgian'),
    ('German', 'German'),
    ('Gaelic; Scottish Gaelic', 'Gaelic; Scottish Gaelic'),
    ('Irish', 'Irish'),
    ('Galician', 'Galician'),
    ('Manx', 'Manx'),
    ('Greek, Modern (1453-', 'Greek, Modern (1453-)'),
    ('Guarani', 'Guarani'),
    ('Gujarati', 'Gujarati'),
    ('Haitian; Haitian Creole', 'Haitian; Haitian Creole'),
    ('Hausa', 'Hausa'),
    ('Hebrew', 'Hebrew'),
    ('Herero', 'Herero'),
    ('Hindi', 'Hindi'),
    ('Hiri Motu', 'Hiri Motu'),
    ('Croatian', 'Croatian'),
    ('Hungarian', 'Hungarian'),
    ('Armenian', 'Armenian'),
    ('Igbo', 'Igbo'),
    ('Icelandic', 'Icelandic'),
    ('Ido', 'Ido'),
    ('Sichuan Yi; Nuosu', 'Sichuan Yi; Nuosu'),
    ('Inuktitut', 'Inuktitut'),
    ('Interlingue; Occidental', 'Interlingue; Occidental'),
    ('Interlingua (International Auxiliary Language Association',
     'Interlingua (International Auxiliary Language Association)'),
    ('Indonesian', 'Indonesian'),
    ('Inupiaq', 'Inupiaq'),
    ('Icelandic', 'Icelandic'),
    ('Italian', 'Italian'),
    ('Javanese', 'Javanese'),
    ('Japanese', 'Japanese'),
    ('Kalaallisut; Greenlandic', 'Kalaallisut; Greenlandic'),
    ('Kannada', 'Kannada'),
    ('Kashmiri', 'Kashmiri'),
    ('Georgian', 'Georgian'),
    ('Kanuri', 'Kanuri'),
    ('Kazakh', 'Kazakh'),
    ('Central Khmer', 'Central Khmer'),
    ('Kikuyu; Gikuyu', 'Kikuyu; Gikuyu'),
    ('Kinyarwanda', 'Kinyarwanda'),
    ('Kirghiz; Kyrgyz', 'Kirghiz; Kyrgyz'),
    ('Komi', 'Komi'),
    ('Kongo', 'Kongo'),
    ('Korean', 'Korean'),
    ('Kuanyama; Kwanyama', 'Kuanyama; Kwanyama'),
    ('Kurdish', 'Kurdish'),
    ('Lao', 'Lao'),
    ('Latin', 'Latin'),
    ('Latvian', 'Latvian'),
    ('Limburgan; Limburger; Limburgish', 'Limburgan; Limburger; Limburgish'),
    ('Lingala', 'Lingala'),
    ('Lithuanian', 'Lithuanian'),
    ('Luxembourgish; Letzeburgesch', 'Luxembourgish; Letzeburgesch'),
    ('Luba-Katanga', 'Luba-Katanga'),
    ('Ganda', 'Ganda'),
    ('Macedonian', 'Macedonian'),
    ('Marshallese', 'Marshallese'),
    ('Malayalam', 'Malayalam'),
    ('Maori', 'Maori'),
    ('Marathi', 'Marathi'),
    ('Malay', 'Malay'),
    ('Micmac', 'Micmac'),
    ('Macedonian', 'Macedonian'),
    ('Malagasy', 'Malagasy'),
    ('Maltese', 'Maltese'),
    ('Mongolian', 'Mongolian'),
    ('Maori', 'Maori'),
    ('Malay', 'Malay'),
    ('Burmese', 'Burmese'),
    ('Nauru', 'Nauru'),
    ('Navajo; Navaho', 'Navajo; Navaho'),
    ('Ndebele, South; South Ndebele', 'Ndebele, South; South Ndebele'),
    ('Ndebele, North; North Ndebele', 'Ndebele, North; North Ndebele'),
    ('Ndonga', 'Ndonga'),
    ('Nepali', 'Nepali'),
    ('Dutch; Flemish', 'Dutch; Flemish'),
    ('Norwegian Nynorsk; Nynorsk, Norwegian', 'Norwegian Nynorsk; Nynorsk, Norwegian'),
    ('Bokmål, Norwegian; Norwegian Bokmål', 'Bokmål, Norwegian; Norwegian Bokmål'),
    ('Norwegian', 'Norwegian'),
    ('Occitan (post 1500', 'Occitan (post 1500)'),
    ('Ojibwa', 'Ojibwa'),
    ('Oriya', 'Oriya'),
    ('Oromo', 'Oromo'),
    ('Ossetian; Ossetic', 'Ossetian; Ossetic'),
    ('Panjabi; Punjabi', 'Panjabi; Punjabi'),
    ('Persian', 'Persian'),
    ('Pali', 'Pali'),
    ('Polish', 'Polish'),
    ('Portuguese', 'Portuguese'),
    ('Pushto; Pashto', 'Pushto; Pashto'),
    ('Quechua', 'Quechua'),
    ('Romansh', 'Romansh'),
    ('Romanian; Moldavian; Moldovan', 'Romanian; Moldavian; Moldovan'),
    ('Romanian; Moldavian; Moldovan', 'Romanian; Moldavian; Moldovan'),
    ('Rundi', 'Rundi'),
    ('Russian', 'Russian'),
    ('Sango', 'Sango'),
    ('Sanskrit', 'Sanskrit'),
    ('Sinhala; Sinhalese', 'Sinhala; Sinhalese'),
    ('Slovak', 'Slovak'),
    ('Slovak', 'Slovak'),
    ('Slovenian', 'Slovenian'),
    ('Northern Sami', 'Northern Sami'),
    ('Samoan', 'Samoan'),
    ('Shona', 'Shona'),
    ('Sindhi', 'Sindhi'),
    ('Somali', 'Somali'),
    ('Sotho, Southern', 'Sotho, Southern'),
    ('Spanish; Castilian', 'Spanish; Castilian'),
    ('Albanian', 'Albanian'),
    ('Sardinian', 'Sardinian'),
    ('Serbian', 'Serbian'),
    ('Swati', 'Swati'),
    ('Sundanese', 'Sundanese'),
    ('Swahili', 'Swahili'),
    ('Swedish', 'Swedish'),
    ('Tahitian', 'Tahitian'),
    ('Tamil', 'Tamil'),
    ('Tatar', 'Tatar'),
    ('Telugu', 'Telugu'),
    ('Tajik', 'Tajik'),
    ('Tagalog', 'Tagalog'),
    ('Thai', 'Thai'),
    ('Tibetan', 'Tibetan'),
    ('Tigrinya', 'Tigrinya'),
    ('Tonga (Tonga Islands', 'Tonga (Tonga Islands)'),
    ('Tswana', 'Tswana'),
    ('Tsonga', 'Tsonga'),
    ('Turkmen', 'Turkmen'),
    ('Turkish', 'Turkish'),
    ('Twi', 'Twi'),
    ('Uighur; Uyghur', 'Uighur; Uyghur'),
    ('Ukrainian', 'Ukrainian'),
    ('Urdu', 'Urdu'),
    ('Uzbek', 'Uzbek'),
    ('Venda', 'Venda'),
    ('Vietnamese', 'Vietnamese'),
    ('Volapük', 'Volapük'),
    ('Welsh', 'Welsh'),
    ('Walloon', 'Walloon'),
    ('Wolof', 'Wolof'),
    ('Xhosa', 'Xhosa'),
    ('Yiddish', 'Yiddish'),
    ('Yoruba', 'Yoruba'),
    ('Zhuang; Chuang', 'Zhuang; Chuang'),
    ('Chinese', 'Chinese'),
    ('Zulu', 'Zulu')

]

countries = [
    ('AF', u'Afghanistan'),
    ('AX', u'\xc5land Islands'),
    ('AL', u'Albania'),
    ('DZ', u'Algeria'),
    ('AS', u'American Samoa'),
    ('AD', u'Andorra'),
    ('AO', u'Angola'),
    ('AI', u'Anguilla'),
    ('AQ', u'Antarctica'),
    ('AG', u'Antigua and Barbuda'),
    ('AR', u'Argentina'),
    ('AM', u'Armenia'),
    ('AW', u'Aruba'),
    ('AU', u'Australia'),
    ('AT', u'Austria'),
    ('AZ', u'Azerbaijan'),
    ('BS', u'Bahamas'),
    ('BH', u'Bahrain'),
    ('BD', u'Bangladesh'),
    ('BB', u'Barbados'),
    ('BY', u'Belarus'),
    ('BE', u'Belgium'),
    ('BZ', u'Belize'),
    ('BJ', u'Benin'),
    ('BM', u'Bermuda'),
    ('BT', u'Bhutan'),
    ('BO', u'Bolivia, Plurinational State of'),
    ('BQ', u'Bonaire, Sint Eustatius and Saba'),
    ('BA', u'Bosnia and Herzegovina'),
    ('BW', u'Botswana'),
    ('BV', u'Bouvet Island'),
    ('BR', u'Brazil'),
    ('IO', u'British Indian Ocean Territory'),
    ('BN', u'Brunei Darussalam'),
    ('BG', u'Bulgaria'),
    ('BF', u'Burkina Faso'),
    ('BI', u'Burundi'),
    ('KH', u'Cambodia'),
    ('CM', u'Cameroon'),
    ('CA', u'Canada'),
    ('CV', u'Cape Verde'),
    ('KY', u'Cayman Islands'),
    ('CF', u'Central African Republic'),
    ('TD', u'Chad'),
    ('CL', u'Chile'),
    ('CN', u'China'),
    ('CX', u'Christmas Island'),
    ('CC', u'Cocos (Keeling Islands)'),
    ('CO', u'Colombia'),
    ('KM', u'Comoros'),
    ('CG', u'Congo'),
    ('CD', u'Congo, The Democratic Republic of the'),
    ('CK', u'Cook Islands'),
    ('CR', u'Costa Rica'),
    ('CI', u"C\xf4te D'ivoire"),
    ('HR', u'Croatia'),
    ('CU', u'Cuba'),
    ('CW', u'Cura\xe7ao'),
    ('CY', u'Cyprus'),
    ('CZ', u'Czech Republic'),
    ('DK', u'Denmark'),
    ('DJ', u'Djibouti'),
    ('DM', u'Dominica'),
    ('DO', u'Dominican Republic'),
    ('EC', u'Ecuador'),
    ('EG', u'Egypt'),
    ('SV', u'El Salvador'),
    ('GQ', u'Equatorial Guinea'),
    ('ER', u'Eritrea'),
    ('EE', u'Estonia'),
    ('ET', u'Ethiopia'),
    ('FK', u'Falkland Islands (Malvinas)'),
    ('FO', u'Faroe Islands'),
    ('FJ', u'Fiji'),
    ('FI', u'Finland'),
    ('FR', u'France'),
    ('GF', u'French Guiana'),
    ('PF', u'French Polynesia'),
    ('TF', u'French Southern Territories'),
    ('GA', u'Gabon'),
    ('GM', u'Gambia'),
    ('GE', u'Georgia'),
    ('DE', u'Germany'),
    ('GH', u'Ghana'),
    ('GI', u'Gibraltar'),
    ('GR', u'Greece'),
    ('GL', u'Greenland'),
    ('GD', u'Grenada'),
    ('GP', u'Guadeloupe'),
    ('GU', u'Guam'),
    ('GT', u'Guatemala'),
    ('GG', u'Guernsey'),
    ('GN', u'Guinea'),
    ('GW', u'Guinea-bissau'),
    ('GY', u'Guyana'),
    ('HT', u'Haiti'),
    ('HM', u'Heard Island and McDonald Islands'),
    ('VA', u'Holy See (Vatican City State)'),
    ('HN', u'Honduras'),
    ('HK', u'Hong Kong'),
    ('HU', u'Hungary'),
    ('IS', u'Iceland'),
    ('IN', u'India'),
    ('ID', u'Indonesia'),
    ('IR', u'Iran, Islamic Republic of'),
    ('IQ', u'Iraq'),
    ('IE', u'Ireland'),
    ('IM', u'Isle of Man'),
    ('IL', u'Israel'),
    ('IT', u'Italy'),
    ('JM', u'Jamaica'),
    ('JP', u'Japan'),
    ('JE', u'Jersey'),
    ('JO', u'Jordan'),
    ('KZ', u'Kazakhstan'),
    ('KE', u'Kenya'),
    ('KI', u'Kiribati'),
    ('KP', u"Korea, Democratic People's Republic of"),
    ('KR', u'Korea, Republic of'),
    ('KW', u'Kuwait'),
    ('KG', u'Kyrgyzstan'),
    ('LA', u"Lao People's Democratic Republic"),
    ('LV', u'Latvia'),
    ('LB', u'Lebanon'),
    ('LS', u'Lesotho'),
    ('LR', u'Liberia'),
    ('LY', u'Libya'),
    ('LI', u'Liechtenstein'),
    ('LT', u'Lithuania'),
    ('LU', u'Luxembourg'),
    ('MO', u'Macao'),
    ('MK', u'Macedonia, The Former Yugoslav Republic of'),
    ('MG', u'Madagascar'),
    ('MW', u'Malawi'),
    ('MY', u'Malaysia'),
    ('MV', u'Maldives'),
    ('ML', u'Mali'),
    ('MT', u'Malta'),
    ('MH', u'Marshall Islands'),
    ('MQ', u'Martinique'),
    ('MR', u'Mauritania'),
    ('MU', u'Mauritius'),
    ('YT', u'Mayotte'),
    ('MX', u'Mexico'),
    ('FM', u'Micronesia, Federated States of'),
    ('MD', u'Moldova, Republic of'),
    ('MC', u'Monaco'),
    ('MN', u'Mongolia'),
    ('ME', u'Montenegro'),
    ('MS', u'Montserrat'),
    ('MA', u'Morocco'),
    ('MZ', u'Mozambique'),
    ('MM', u'Myanmar'),
    ('NA', u'Namibia'),
    ('NR', u'Nauru'),
    ('NP', u'Nepal'),
    ('NL', u'Netherlands'),
    ('NC', u'New Caledonia'),
    ('NZ', u'New Zealand'),
    ('NI', u'Nicaragua'),
    ('NE', u'Niger'),
    ('NG', u'Nigeria'),
    ('NU', u'Niue'),
    ('NF', u'Norfolk Island'),
    ('MP', u'Northern Mariana Islands'),
    ('NO', u'Norway'),
    ('OM', u'Oman'),
    ('PK', u'Pakistan'),
    ('PW', u'Palau'),
    ('PS', u'Palestinian Territory, Occupied'),
    ('PA', u'Panama'),
    ('PG', u'Papua New Guinea'),
    ('PY', u'Paraguay'),
    ('PE', u'Peru'),
    ('PH', u'Philippines'),
    ('PN', u'Pitcairn'),
    ('PL', u'Poland'),
    ('PT', u'Portugal'),
    ('PR', u'Puerto Rico'),
    ('QA', u'Qatar'),
    ('RE', u'R\xe9union'),
    ('RO', u'Romania'),
    ('RU', u'Russian Federation'),
    ('RW', u'Rwanda'),
    ('BL', u'Saint Barth\xe9lemy'),
    ('SH', u'Saint Helena, Ascension and Tristan Da Cunha'),
    ('KN', u'Saint Kitts and Nevis'),
    ('LC', u'Saint Lucia'),
    ('MF', u'Saint Martin (French Part)'),
    ('PM', u'Saint Pierre and Miquelon'),
    ('VC', u'Saint Vincent and the Grenadines'),
    ('WS', u'Samoa'),
    ('SM', u'San Marino'),
    ('ST', u'Sao Tome and Principe'),
    ('SA', u'Saudi Arabia'),
    ('SN', u'Senegal'),
    ('RS', u'Serbia'),
    ('SC', u'Seychelles'),
    ('SL', u'Sierra Leone'),
    ('SG', u'Singapore'),
    ('SX', u'Sint Maarten (Dutch Part)'),
    ('SK', u'Slovakia'),
    ('SI', u'Slovenia'),
    ('SB', u'Solomon Islands'),
    ('SO', u'Somalia'),
    ('ZA', u'South Africa'),
    ('GS', u'South Georgia and the South Sandwich Islands'),
    ('SS', u'South Sudan'),
    ('ES', u'Spain'),
    ('LK', u'Sri Lanka'),
    ('SD', u'Sudan'),
    ('SR', u'Suriname'),
    ('SJ', u'Svalbard and Jan Mayen'),
    ('SZ', u'Swaziland'),
    ('SE', u'Sweden'),
    ('CH', u'Switzerland'),
    ('SY', u'Syrian Arab Republic'),
    ('TW', u'Taiwan, Province of China'),
    ('TJ', u'Tajikistan'),
    ('TZ', u'Tanzania, United Republic of'),
    ('TH', u'Thailand'),
    ('TL', u'Timor-leste'),
    ('TG', u'Togo'),
    ('TK', u'Tokelau'),
    ('TO', u'Tonga'),
    ('TT', u'Trinidad and Tobago'),
    ('TN', u'Tunisia'),
    ('TR', u'Turkey'),
    ('TM', u'Turkmenistan'),
    ('TC', u'Turks and Caicos Islands'),
    ('TV', u'Tuvalu'),
    ('UG', u'Uganda'),
    ('UA', u'Ukraine'),
    ('AE', u'United Arab Emirates'),
    ('GB', u'United Kingdom'),
    ('US', u'United States'),
    ('UM', u'United States Minor Outlying Islands'),
    ('UY', u'Uruguay'),
    ('UZ', u'Uzbekistan'),
    ('VU', u'Vanuatu'),
    ('VE', u'Venezuela, Bolivarian Republic of'),
    ('VN', u'Viet Nam'),
    ('VG', u'Virgin Islands, British'),
    ('VI', u'Virgin Islands, U.S.'),
    ('WF', u'Wallis and Futuna'),
    ('EH', u'Western Sahara'),
    ('YE', u'Yemen'),
    ('ZM', u'Zambia'),
    ('ZW', u'Zimbabwe')
]
professors = [
    ("Monika Abramenko", "Abramenko,Monika"),
    ("Scott T. Acton", "Acton,Scott T."),
    ("Sean R. Agnew", "Agnew,Sean R."),
    ("Negin Alemazkoor", "Alemazkoor, Negin"),
    ("Homa Alemzadeh", "Alemzadeh, Homa"),
    ("Timothy E. Allen", "Allen, Timothy E."),
    ("Eric Anderson", "Anderson, Eric"),
    ("Panagiotis Apostolellis", "Apostolellis, Panagiotis"),
    ("Robert Archer", "Archer, Robert"),
    ("Robert Reid Bailey", "Bailey, Robert Reid"),
    ("Prasanna Venkata Balachandran", "Balachandran, Prasanna Venkata"),
    ("Catherine Baritaud", "Baritaud,	Catherine"),
    ("Nicolas S. Barker", "Barker,	Nicolas S."),
    ("Shannon Barker", "Barker,	Shannon"),
    ("Thomas H. Barker", "Barker,	Thomas H."),
    ("Adam Barnes", "Barnes,	Adam"),
    ("Laura Barnes", "Barnes,	Laura"),
    ("Christopher Barrett", "Barrett,	Christopher"),
    ("Hilary Bart-Smith", "Bart-Smith,	Vicente"),
    ("Nada Basit", "Basit,	Nada"),
    ("Madhur Behl", "Behl,	Madhur"),
    ("Peter A. Beling", "Beling,	Peter A."),
    ("Andreas Beling", "Beling,	Andreas"),
    ("Craig H. Benson", "Benson,	Craig H."),
    ("Bryan W. Berger", "Berger,	Bryan W."),
    ("Rosalyn W. Berne", "Berne,	Rosalyn W."),
    ("Nicola Bezzo", "Bezzo,	Nicola"),
    ("Charles Blankenship", "Blankenship,	Charles"),
    ("Silvia S. Blemker", "Blemker,	Silvia S."),
    ("Aaron Bloomfield", "Bloomfield,	Aaron"),
    ("Mehdi Boukhechba", "Boukhechba,	Mehdi"),
    ("Steven Michael Bowers", "Bowers,	Steven Michael"),
    ("Donald E. Brown", "Brown,	Donald E."),
    ("Nathan J. Brunelle", "Brunelle,	Nathan J."),
    ("Lindsay Burden", "Burden,	Lindsay"),
    ("James T. Burns", "Burns,	James T."),
    ("Liheng Cai", "Cai,	Liheng"),
    ("Benton H. Calhoun", "Calhoun,	Benton H."),
    ("Steven Richard Caliari", "Caliari,	Steven Richard"),
    ("Joe C. Campbell", "Campbell,	Joe C."),
    ("Bradford J. Campbell", "Campbell,	Bradford J."),
    ("W Carlson", "Carlson,	W"),
    ("Giorgio Carta", "Carta,	Giorgio"),
    ("Qing Chang", "Chang,	Qing"),
    ("Harsha K. Chelliah", "Chelliah,	Harsha K."),
    ("Tong Donna Chen", "Chen,	Tong Donna"),
    ("Joshua J. Choi", "Choi,	Joshua J."),
    ("George Joseph Christ", "Christ,	George Joseph"),
    ("Andres F. Clarens", "Clarens,	Andres F."),
    ("James P. Cohoon", "Cohoon,	James P."),
    ("/238 RESULTS", "RESULTS,	/238"),
    ("Teresa B. Culver", "Culver,	Teresa B."),
    ("Jack W. Davidson", "Davidson,	Jack W."),
    ("Robert J. Davis", "Davis,	Robert J."),
    ("Chloe Dedic", "Dedic,	Chloe"),
    ("Todd A DeLong", "DeLong,	Todd A"),
    ("Craig Dill", "Dill,	Craig"),
    ("Haibo Dong", "Dong,	Haibo"),
    ("Afsaneh Doryab", "Doryab,	Afsaneh"),
    ("Joanne B. Dugan", "Dugan,	Joanne B."),
    ("Matthew Dwyer", "Dwyer,	Matthew"),
    ("Sebastian Elbaum", "Elbaum,	Sebastian"),
    ("Dana M. Elzey", "Elzey,	Dana M."),
    ("William S. Epling", "Epling,	William S."),
    ("Keivan Esfarjani", "Esfarjani,	Keivan"),
    ("David Evans", "Evans,	David"),
    ("Lu Feng", "Feng,	Lu"),
    ("Sean Ferguson", "Ferguson,	Sean"),
    ("Roger L. Fittro", "Fittro,	Roger L."),
    ("James M. Fitz-Gerald", "Fitz-Gerald,	James"),
    ("Preston Fletcher", "Fletcher,	Preston"),
    ("Jerrold A. Floro", "Floro,	Jerrold A."),
    ("Mark Richard Floryan", "Floryan,	Mark Richard"),
    ("Rider W. Foley", "Foley,	Rider W."),
    ("Roseanne Ford", "Ford,	Roseanne"),
    ("Diana Franco Duran", "Duran,	Diana Franco"),
    ("Bernard Fulgham", "Fulgham,	Bernard"),
    ("Tomonari Furukawa", "Furukawa,	Tomonari"),
    ("Gavin T. Garner", "Garner,	Gavin T."),
    ("Geoffrey Matthew Geise", "Geise,	Geoffrey Matthew"),
    ("Gregory J. Gerling", "Gerling,	Gregory J."),
    ("Avik Ghosh", "Ghosh,	Avik"),
    ("Gaurav Giri", "Giri,	Gaurav"),
    ("Jonathan L Goodall", "Goodall,	Jonathan L"),
    ("Michael E. Gorman", "Gorman,	Michael E."),
    ("Christopher P. Goyne", "Goyne,	Christopher P."),
    ("Daniel Graham", "Graham,	Daniel"),
    ("David L. Green", "Green,	David L."),
    ("Donald Richieri Griffin", "Griffin,	Donald Richieri"),
    ("Andrew S. Grimshaw", "Grimshaw,	Andrew S."),
    ("James F. Groves", "Groves,	James F."),
    ("Gianluca Guadagni", "Guadagni,	Gianluca"),
    ("William H. Guilford", "Guilford,	William H."),
    ("Mool C. Gupta", "Gupta,	Mool C."),
    ("757-766-4608", "7577664608,	),"),
    ("Devin K. Harris", "Harris,	Devin K."),
    ("Farzad Farnoud Hassanzadeh", "Hassanzadeh,	Farzad Farnoud"),
    ("Christian Hellings", "Hellings,	Christian"),
    ("Brian P. Helmke", "Helmke,	Brian P."),
    ("Seongkook Heo", "Heo,	Seongkook"),
    ("Arsalan Heydarian", "Heydarian,	Arsalan"),
    ("Chris Highley", "Highley,	Chris"),
    ("Jeffrey W. Holmes", "Holmes,	Jeffrey W."),
    ("Patrick E. Hopkins", "Hopkins,	Patrick E."),
    ("Barry Horowitz", "Horowitz,	Barry"),
    ("Thomas B. Horton", "Horton,	Thomas B."),
    ("John A. Hossack", "Hossack,	John A."),
    ("John Hott", "Hott,	John"),
    ("James M. Howe", "Howe,	James M."),
    ("Marty A. Humphrey", "Humphrey,	Marty A."),
    ("Jon Fredrick Ihlefeld", "Ihlefeld,	Jon Fredrick"),
    ("Tariq Iqbal", "Iqbal,	Tariq"),
    ("Kevin A. Janes", "Janes,	Kevin A."),
    ("Yangfeng Ji", "Ji,	Yangfeng"),
    ("Barry W. Johnson", "Johnson,	Barry W."),
    ("Robert G. Kelly", "Kelly,	Robert G."),
    ("Richard Kent", "Kent,	Richard"),
    ("Jason R. Kerrigan", "Kerrigan,	Jason R."),
    ("Samira Manabi Khan", "Khan,	Samira Manabi"),
    ("Leidy Klotz", "Klotz,	Leidy"),
    ("Carl R. Knospe", "Knospe,	Carl R."),
    ("Gary M. Koenig", "Koenig,	Gary M."),
    ("Anne Kromkowski", "Kromkowski,	Anne"),
    ("Roman Krzysztofowicz", "Krzysztofowicz,	Roman"),
    ("Tsai-Hsuan Tsai-Hsuan Ku", "Ku,	Tsai-Hsuan Tsai-Hsuan"),
    ("Yonghwi Kwon", "Kwon,	Yonghwi"),
    ("Venkataraman Lakshmi", "Lakshmi,	Venkataraman"),
    ("James H. Lambert", "Lambert,	James H."),
    ("Kyle J. Lampe", "Lampe,	Kyle J."),
    ("James Lark", "Lark,	James"),
    ("Benjamin Laugelli", "Laugelli,	Benjamin"),
    ("Matthew J. Lazzara", "Lazzara,	Matthew J."),
    ("Kyusang Lee", "Lee,	Kyusang"),
    ("Rachel A Letteri", "Letteri,	Rachel A"),
    ("Xiaodong Li", "Li,	Xiaodong"),
    ("Meiqin Li", "Li,	Meiqin"),
    ("Jundong Li", "Li,	Jundong"),
    ("Arthur W. Lichtenberger", "Lichtenberger,	Arthur W."),
    ("Zongli Lin", "Lin,	Zongli"),
    ("Xiaozhu Lin", "Lin,	Xiaozhu"),
    ("Eric Loth", "Loth,	Eric"),
    ("Garrick E. Louis", "Louis,	Garrick E."),
    ("Lin Ma", "Ma,	Lin"),
    ("Hui Ma", "Ma,	Hui"),
    ("Ji Ma", "Ma,	Ji"),
    ("Mohammad Mahmoody Ghidary", "Ghidary,	Mohammad Mahmoody"),
    ("Deepyaman Maiti", "Maiti,	Deepyaman"),
    ("Worthy N. Martin", "Martin,	Worthy N."),
    ("Richard Martukanitz", "Martukanitz,	Richard"),
    ("Frank William Mauldin", "Mauldin,	Frank William"),
    ("Frances McBride", "McBride,	Frances"),
    ("Paul McBurney", "McBurney,	Paul"),
    ("Stephen John McDonnell", "McDonnell,	Stephen John"),
    ("Manouchehr Mohajeri", "Mohajeri,	Manouchehr"),
    ("Michael Momot", "Momot,	Michael"),
    ("Diana Morris", "Morris,	Diana"),
    ("Henning Mortveit", "Mortveit,	Henning"),
    ("Kristen Naegle", "Naegle,	Kristen"),
    ("Kathryn A. Neeley", "Neeley,	Kathryn A."),
    ("Nhat Nguyen", "Nguyen,	Nhat"),
    ("Pamela M. Norris", "Norris,	Pamela M."),
    ("Peter D. Norton", "Norton,	Peter D."),
    ("Toluwalogo Odumosu", "Odumosu,	Toluwalogo"),
    ("Elizabeth J. Opila", "Opila,	Elizabeth J."),
    ("Vicente Ordonez-Roman", "Ordonez-Roman,	Vicente"),
    ("Elizabeth Orrico", "Orrico,	Elizabeth"),
    ("Osman E. Ozbulut", "Ozbulut,	Osman E."),
    ("Matthew B. Panzer", "Panzer,	Matthew B."),
    ("Chris Paolucci", "Paolucci,	Chris"),
    ("B. Brian Park", "Park,	B. Brian"),
    ("Lisa Colosi Peterson", "Peterson,	Lisa Colosi"),
    ("Raymond S Pettit", "Pettit,	Raymond S"),
    ("Marek-Jerzy Pindera", "Pindera,	Marek-Jerzy"),
    ("Stacie Pisano", "Pisano,	Stacie"),
    ("Michael D Porter", "Porter,	Michael D"),
    ("Harry C. Powell", "Powell,	Harry C."),
    ("Upsorn Praphamontripong", "Praphamontripong,	Upsorn"),
    ("Richard J. Price", "Price,	Richard J."),
    ("George Prpich", "Prpich,	George"),
    ("Yanjun Qi", "Qi,	Yanjun"),
    ("Daniel Benjamin Quinn", "Quinn,	Daniel Benjamin"),
    ("Julianne Dorothy Quinn", "Quinn,	Julianne Dorothy"),
    ("Ann Reimers", "Reimers,	Ann"),
    ("Petra Reinke", "Reinke,	Petra"),
    ("Charles Reiss", "Reiss,	Charles"),
    ("Sara Riggs", "Riggs,	Sara"),
    ("Robert Riggs", "Riggs,	Robert"),
    ("Gustavo Kunde Rohde", "Rohde,	Gustavo Kunde"),
    ("Mitchel C. Rosen", "Rosen,	Mitchel C."),
    ("Jonathan Rosen", "Rosen,	Jonathan"),
    ("Megan Ryals", "Ryals,	Megan"),
    ("Robert S. Salzar", "Salzar,	Robert S."),
    ("William T. Scherer", "Scherer,	William T."),
    ("John R. Scully", "Scully,	John R."),
    ("Bryn Elizabeth Seabrook", "Seabrook,	Bryn Elizabeth"),
    ("Majid Shafiee-Jood", "Shafiee-Jood,	Majid"),
    ("Cong Shen", "Shen,	Cong"),
    ("Haiying Shen", "Shen,	Haiying"),
    ("Mark S. Sherriff", "Sherriff,	Mark S."),
    ("Nikhil Shukla", "Shukla,	Nikhil"),
    ("Nikolaos D. Sidiropoulos", "Sidiropoulos,	Nikolaos D."),
    ("Kevin Skadron", "Skadron,	Kevin"),
    ("David L. Slutzky", "Slutzky,	David L."),
    ("Mary Smith", "Smith,	Mary"),
    ("Natasha Leigh Smith", "Smith,	Natasha Leigh"),
    ("James A. Smith", "Smith,	James A."),
    ("Brian L. Smith", "Smith,	Brian L."),
    ("Mary Lou Soffa", "Soffa,	Mary Lou"),
    ("Julia Spencer", "Spencer,	Julia"),
    ("Mircea R. Stan", "Stan,	Mircea R."),
    ("John A Stankovic", "Stankovic,	John A"),
    ("Kevin J. Sullivan", "Sullivan,	Kevin J."),
    ("Yixin Sun", "Sun,	Yixin"),
    ("Tao Sun", "Sun,	Tao"),
    ("Nathan Swami", "Swami,	Nathan"),
    ("Gang Tao", "Tao,	Gang"),
    ("Yuan Tian", "Tian,	Yuan"),
    ("Luther A. Tychonievich", "Tychonievich,	Luther A."),
    ("Ronald Unnerstall", "Unnerstall,	Ronald"),
    ("Ashish Venkat", "Venkat,	Ashish"),
    ("Haydn N. Wadley", "Wadley,	Haydn N."),
    ("Hongning Wang", "Wang,	Hongning"),
    ("Robert M. Weikle", "Weikle,	Robert M."),
    ("Daniel S. Weller", "Weller,	Daniel S."),
    ("Cameron Whitehouse", "Whitehouse,	Cameron"),
    ("Keith A. Williams", "Williams,	Keith A."),
    ("Ronald D. Williams", "Williams,	Ronald D."),
    ("Houston G Wood", "Wood,	Houston G"),
    ("David Wu", "Wu,	David"),
    ("Caitlin Donahue Wylie", "Wylie,	Caitlin Donahue"),
    ("Baoxing Xu", "Xu,	Baoxing"),
    ("Haifeng Xu", "Xu,	Haifeng"),
    ("Xu Yi", "Yi,	Xu"),
    ("Giovanni Zangari", "Zangari,	Giovanni"),
    ("Mona Zebarjadi", "Zebarjadi,	Mona"),
    ("Miaomiao Zhang", "Zhang,	Miaomiao"),
    ("Aidong Zhang", "Zhang,	Aidong"),
    ("Leonid V. Zhigilei", "Zhigilei,	Leonid V."),
    ("Bicheng Zhou", "Zhou,Bicheng"),
    ("Eli R Zunder", "Zunder, Eli R ")
]

Timezone = (
    ('ANAT', "Anadyr"),
    ('AEDT', "Melbourne"),
    ('AEST', "Brisbane"),
    ('JST', "Tokyo"),
    ('CST', "Beijing"),
    ('WIB', "Jakarta"),
    ('UZT', "Tashkent"),
    ('GST', "Dubai"),
    ('MSK', "Moscow"),
    ('CEST', "Brussels"),
    ('BST', "London"),
    ('GMT', "Accra"),
    ('CVT', "Praia"),
    ('WGST', "Nuuk"),
    ('ART', "Buenos Aires"),
    ('EDT', "New York"),
    ('CDT', "Mexico City"),
    ('PDT', "Los Angeles"),
    ('AKDT', "Anchorage"),
    ('HDT', "Adak"),
    ('HST', "Honolulu"),
    ('NUT', "Alofi"),
    ('AoE', "Baker Island"),
    ('LINT', "Kiritimati"),
    ('NZDT', "Auckland"),
    ('ACDT', "Adelaide"),
    ('ACST', "Darwin"),
    ('MMT', "Yangon"),
    ('IST', "New Delhi"),
    ('AFT', "Kabul"),
    ('IRST', "Tehran"),
    ('NDT', "St. John's"),
    ('MART', "Taiohae"),
    ('CHADT', "Chatham Islands"),
    ('ACWST', "Eucla"),
    ('NPT', "Kathmandu")
)
Course = (
    ('APMA', "APMA"),
    ('BME', "BME"),
    ('CS', "CS"),
    ('CE', "CE"),
    ('CHE', "CHE"),
    ('CPE', "CPE"),
    ('ECE', "ECE"),
    ('MAE', "MAE"),
    ('STS', "STS")
)

Lecture = (
    ('WEB_BASED', "WEB_BASED"),
    ('IN_PERSON', "IN_PERSON")
)

majors = [
    ('African American & African Studies', 'African American & African Studies'),
    ('American Studies', 'American Studies'),
    ('Anthropology', 'Anthropology'),
    ('Art History', 'Art History'),
    ('Art, Studio', 'Art, Studio'),
    ('Astronomy', 'Astronomy'),
    ('Astronomy-Physics', 'Astronomy-Physics'),
    ('Biology', 'Biology'),
    ('Chemistry', 'Chemistry'),
    ('Chinese Language & Literature', 'Chinese Language & Literature'),
    ('Classics', 'Classics'),
    ('Cognitive Science', 'Cognitive Science'),
    ('Comparative Literature', 'Comparative Literature'),
    ('Computer Science', 'Computer Science'),
    ('Drama', 'Drama'),
    ('East Asian Studies', 'East Asian Studies'),
    ('Economics', 'Economics'),
    ('English', 'English'),
    ('Environmental Sciences', 'Environmental Sciences'),
    ('Environmental Thought & Practice', 'Environmental Thought & Practice'),
    ('French', 'French'),
    ('German', 'German'),
    ('Global Studies', 'Global Studies'),
    ('History', 'History'),
    ('Human Biology', 'Human Biology'),
    ('Italian', 'Italian'),
    ('Japanese Language & Literature', 'Japanese Language & Literature'),
    ('Jewish Studies', 'Jewish Studies'),
    ('Latin American Studies', 'Latin American Studies'),
    ('Linguistics', 'Linguistics'),
    ('Mathematics', 'Mathematics'),
    ('Media Studies', 'Media Studies'),
    ('Medieval Studies', 'Medieval Studies'),
    ('Middle Eastern and South Asian Languages and Cultures', 'Middle Eastern and South Asian Languages and Cultures'),
    ('Music', 'Music'),
    ('Neuroscience', 'Neuroscience'),
    ('Philosophy', 'Philosophy'),
    ('Physics', 'Physics'),
    ('Political and Social Thought', 'Political and Social Thought'),
    ('Political Philosophy, Policy, and Law', 'Political Philosophy, Policy, and Law'),
    ('Politics', 'Politics'),
    ('Psychology', 'Psychology'),
    ('Religious Studies', 'Religious Studies'),
    ('Slavic Languages and Literatures', 'Slavic Languages and Literatures'),
    ('Sociology', 'Sociology'),
    ('South Asian Studies', 'South Asian Studies'),
    ('Spanish', 'Spanish'),
    ('Statistics', 'Statistics'),
    ('Women, Gender, and Sexuality', 'Women, Gender, and Sexuality'),
    ('Aerospace Engineering', 'Aerospace Engineering'),
    ('Biomedical Engineering', 'Biomedical Engineering'),
    ('Chemical Engineering', 'Chemical Engineering'),
    ('Civil Engineering', 'Civil Engineering'),
    ('Computer Engineering', 'Computer Engineering'),
    ('Computer Science', 'Computer Science'),
    ('Electrical Engineering', 'Electrical Engineering'),
    ('Engineering Science', 'Engineering Science'),
    ('Mechanical Engineering', 'Mechanical Engineering'),
    ('Systems Engineering', 'Systems Engineering'),
    ('Accounting', 'Accounting'),
    ('Finance', 'Finance'),
    ('Information Technology', 'Information Technology'),
    ('Management', 'Management'),
    ('Marketing', 'Marketing'),
    ('School of Architecture', 'School of Architecture'),
    ('Architectural History', 'Architectural History'),
    ('Architecture', 'Architecture'),
    ('Urban & Environmental Planning', 'Urban & Environmental Planning'),
    ('School of Nursing', 'School of Nursing'),
    ('Bachelor of Science in Nursing (BSN)', 'Bachelor of Science in Nursing (BSN)'),
    ('RN to BSN', 'RN to BSN'),
    ('Batten School of Leadership and Public Policy', 'Batten School of Leadership and Public Policy'),
    ('B.A. in Public Policy and Leadership', 'B.A. in Public Policy and Leadership'),
    (
    'Accelerated B.A./Master of Public Policy (MPP) Program', 'Accelerated B.A./Master of Public Policy (MPP) Program'),
    ('Curry School of Education', 'Curry School of Education'),
    ('Kinesiology', 'Kinesiology'),
    ('Speech Communications Disorders', 'Speech Communications Disorders'),
    ('Youth & Social Innovation', 'Youth & Social Innovation'),
    ('Teacher Education majors (B.S.Ed.)', 'Teacher Education majors (B.S.Ed.)'),
    ('Early Childhood Education', 'Early Childhood Education'),
    ('Elementary Education', 'Elementary Education'),
    ('Special Education', 'Special Education'),
    ('Teacher Education (listing-graduate Master of Teaching)',
     'Teacher Education (listing-graduate Master of Teaching)'),
    ('Elementary Education', 'Elementary Education'),
    ('English Education', 'English Education'),
    ('English as a Second Language Education', 'English as a Second Language Education'),
    ('Foreign Language Education', 'Foreign Language Education'),
    ('Mathematics Education', 'Mathematics Education'),
    ('Science Education', 'Science Education'),
    ('Social Studies Education', 'Social Studies Education'),
    ('Special Education', 'Special Education')
]
#
# majors = (
#     ('cs', 'Computer Science'),
#     ('other', 'non-CS major')
# )

years = (
    ('2020', '2020'),
    ('2021', '2021'),
    ('2022', '2022'),
    ('2023', '2023'),
    ('2024', '2024'),
    ('2025', '2025'),
    ('2026', '2026'),
    ('2027', '2027'),
)

uva_classes = (
    ('CS3240', 'CS3240'),
    ('lame class', 'lame class'),
)


group_members = (
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
)

sections = list(zip(range(1000, 5000), range(1000, 5000)))
